### ISSUE TITLE
no mtcnn_detector , no face_preprocess

### ISSUE THREAD

**Issue by eeric** [pterhoer/FaceImageQuality#10]
please provided their link, thanks.

**Comment by jankolf** [comment]
Hi,
the mtcnn_detector and the face_preprocess are part of the [Insightface](https://github.com/deepinsight/insightface) repository.
You have to download the repository, extract it, and specify the path to the extracted Insightface code in the _InsightFace_ class in our source code:
[`insightface_path:str = "./insightface/"`](https://github.com/pterhoer/FaceImageQuality/blob/b59b2ec3c58429ee867dee25a4d8165b9c65d304/face_image_quality.py#L25
)
The modules are imported automatically from their source code.

I hope this helps.
If you have further questions, please do not hesitate to ask them.

Best,
Jan

**Comment by eeric** [comment]
thank you!
