### ISSUE TITLE
preprocess

### ISSUE THREAD

**Issue by CrystalWong2** [pterhoer/FaceImageQuality#12]
Hello，when I tried to run the code. I found missing two module that in face_image_quality.py line 73 and line 74. I
 can download some mtcnn implement inmxnet version.But I don't know the rule of preprocess.py. Can you share the file or share some detail that I can reproduce it. Thank you.

**Comment by jankolf** [comment]
Hi,
[we explained this problem in this issue](https://github.com/pterhoer/FaceImageQuality/issues/10).
You need to download the Insightface repository, extract it and pass the path to the Insightface class.

Best,
Jan

**Comment by CrystalWong2** [comment]
@jankolf Thank you so much.  After I read paper，I doubt that “Ser-fiq score higher means that the image quality better”. I am not sure about it
