### ISSUE TITLE
about same model and on-top model

### ISSUE THREAD

**Issue by liiiiiiiiil** [pterhoer/FaceImageQuality#20]
Hi pterhoer:
    Your code seems to be the "on-top model" method of SER, I am trying to transfer it to "same model" but faild. could you please release the “same model” code？

**Comment by pterhoer** [comment]
Hi liiiiiiiiil,

we only published the code for the "same model" using ArcFace.
As written in the description, we apply our SER-FIQ concept on this model https://github.com/deepinsight/insightface.

Best
Philipp

**Comment by liiiiiiiiil** [comment]
Thanks！
