### ISSUE TITLE
np.load(f"{data_path}/pre_fc1_weights.npy") error 

### ISSUE THREAD

**Issue by xiaosongshine** [pterhoer/FaceImageQuality#24]
ValueError: cannot reshape array of size 7618528 into shape (512,25088)

**Comment by jankolf** [comment]
Hi @xiaosongshine 
what weights are you trying to load? The weights stored in git already have the shape (512, 25088).
It appears that you are loading weights of another model via numpy, but this does not match the model used in our code. Please describe your problem in more detail, which weights and model you are using and where exactly the error occurs.

Best,
Jan

**Comment by xiaosongshine** [comment]
Thank when i redownload this file，the error fix。
