### ISSUE TITLE
results is ok？

### ISSUE THREAD

**Issue by xiaosongshine** [pterhoer/FaceImageQuality#25]
SER-FIQ quality score of image 1 is 0.8926710573645206

SER-FIQ quality score of image 2 is 0.8782863740164669

**Comment by jankolf** [comment]
Hi @xiaosongshine
both scores look fine. They can change based on the amount of forward passes used and the dropout layer.

Best,
Jan

**Comment by pterhoer** [comment]
Hi xiaosongshine,

The unnormalized quality range is narrow for the human perception. We already discussed the problem here:
https://github.com/pterhoer/FaceImageQuality/issues/3#issuecomment-644568080

The scores look fine, image 1 is of much higher utility than image 2.

Best
Philipp
