### ISSUE TITLE
scores of lfw dataset are all around 0.89

### ISSUE THREAD

**Issue by sitadivon** [pterhoer/FaceImageQuality#26]
Hello Philipp,

I am trying to reproduce your experiment, but encountered a strange phenomenon. I calculated all scores of lfw database and plotted the distribution of these scores. The scores are all around 0.89. Is this result normal?

![image](https://user-images.githubusercontent.com/34540032/99475276-361c1300-2989-11eb-8439-92c770b1bb00.png)

I'll be very appreciated if you could help me.

Best,
Sitadivon

**Comment by pterhoer** [comment]
Hi Sitadivon,

the result is normal. The quality range itself is very narrow, which does not affect the quality assessment. So, just adapt the x-range :)

You can find more information in older issues like this one:
https://github.com/pterhoer/FaceImageQuality/issues/3#issuecomment-644568080

Best,
Philipp

**Comment by sitadivon** [comment]
Thanks!
