### ISSUE TITLE
i run this code but error for this

### ISSUE THREAD

**Issue by jaffe-fly** [pterhoer/FaceImageQuality#27]
RuntimeError: simple_bind error. Arguments:
data: (1, 3, 112, 112)

what should i do?

**Comment by jankolf** [comment]
Hi @jaffe-fly
could you please explain your problem in more detail? Have you installed all packages and programs according to the instructions?

Best,
Jan

**Comment by zhaowendao30** [comment]
I have the same error, do you solve it?

**Comment by zhaowendao30** [comment]
RuntimeError: simple_bind error. Arguments: data : (1, 3, 112, 112)

**Comment by jaffe-fly** [comment]
> Hi @jaffe-fly
> could you please explain your problem in more detail? Have you installed all packages and programs according to the instructions?
> 
> Best,
> Jan
![image](https://user-images.githubusercontent.com/49515380/101133670-287eb280-3644-11eb-87f8-25eaa517e470.png)
![image](https://user-images.githubusercontent.com/49515380/101133691-33394780-3644-11eb-8fe8-35f5fdcb80a3.png)

**Comment by zhaowendao30** [comment]
my error just like yours, someone say that we should install newer mxnet, like mxnetcu10, but I didn't solve it.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "pterhoer/FaceImageQuality"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月4日(星期五) 下午3:20
收件人:&nbsp;"pterhoer/FaceImageQuality"<FaceImageQuality@noreply.github.com&gt;;
抄送:&nbsp;"赵闻道"<2294580367@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [pterhoer/FaceImageQuality] i run this code but error for this (#27)





  
Hi @jaffe-fly
 could you please explain your problem in more detail? Have you installed all packages and programs according to the instructions?
 
Best,
 Jan

**Comment by jaffe-fly** [comment]
> my error just like yours, someone say that we should install newer mxnet, like mxnetcu10, but I didn't solve it.
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "pterhoer/FaceImageQuality" <notifications@github.com&gt;; 发送时间:&nbsp;2020年12月4日(星期五) 下午3:20 收件人:&nbsp;"pterhoer/FaceImageQuality"<FaceImageQuality@noreply.github.com&gt;; 抄送:&nbsp;"赵闻道"<2294580367@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;; 主题:&nbsp;Re: [pterhoer/FaceImageQuality] i run this code but error for this (#27) Hi @jaffe-fly could you please explain your problem in more detail? Have you installed all packages and programs according to the instructions? Best, Jan — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

I am also installed,but not work !!!

**Comment by jankolf** [comment]
Hi @jaffe-fly , @zhaowendao30 ,
based on the stack trace it could be that your GPU memory is already full or is too small for the Mxnet model.
In @jaffe-fly first image it says
> cudaMalloc retry failed: out of memory

You can try to work around this problem by changing the Mxnet context from gpu to cpu in the code.
For this you can change [**mx.gpu(0)** to **mx.cpu(0)** in this line](https://github.com/pterhoer/FaceImageQuality/blob/d9eff503098e16c622b0fb37c4d5859a6f6b49c4/face_image_quality.py#L61l).
Please check if this resolves your issues.

Best,
Jan

**Comment by zhaowendao30** [comment]
I solve it, my cuda is 11.0, but mxnet is mxnet-cu102, so, we should create a envs that cuda is 10.2.
