### ISSUE TITLE
No module named 'face_preprocess'

### ISSUE THREAD

**Issue by yangzilongdmgy** [pterhoer/FaceImageQuality#28]
I have passed the path to the Insightface repository  to the InsightFace class in face_image_quality.py, but it still says:
Traceback (most recent call last):
  File "serfiq_example.py", line 9, in <module>
    insightface_model = InsightFace()
  File "/data/xxx/open_source_code/FaceImageQuality/face_image_quality.py", line 74, in __init__
    from face_preprocess import preprocess
ModuleNotFoundError: No module named 'face_preprocess'

**Comment by jankolf** [comment]
Hi,
many thanks for creating this issue. It seems that the developers have changed the code structure and therefore the required directories no longer exist.
[Please clone/download the insightface repository at that specific time, the git repository at needed state is linked in here.](https://github.com/deepinsight/insightface/tree/60bb5829b1d76bfcec7930ce61c41dde26413279)
If it works now or if there are any further problems, please let us know.

Best,
Jan

**Comment by yangzilongdmgy** [comment]
Thank you so much, it works well now!
