### ISSUE TITLE
All image's score same

### ISSUE THREAD

**Issue by zhaowendao30** [pterhoer/FaceImageQuality#29]
![image](https://user-images.githubusercontent.com/49309820/101467577-7285d200-397d-11eb-9b90-194e68826bdc.png)

**Comment by zhaowendao30** [comment]
what should i do? Setting something?

**Comment by jankolf** [comment]
Hi,
[please check the answer in this issue, where the scores were described as well.](https://github.com/pterhoer/FaceImageQuality/issues/3#issuecomment-644568080)
The results are ok and totally normal. SER-FIQ can produce narrow score ranges, you can read more [here](https://github.com/pterhoer/FaceImageQuality/issues/26#issuecomment-729496107) and about quality thresholds [here](https://github.com/pterhoer/FaceImageQuality/issues/21#issuecomment-709004710).

Best,
Jan

**Comment by zhaowendao30** [comment]
ok，thanks for your reply!
