### ISSUE TITLE
Why use batch normalization and L2 normalization in SERFIQ?

### ISSUE THREAD

**Issue by Walstruzz** [pterhoer/FaceImageQuality#30]
* First, I know insightface use cosine distance as similarity (so normalization is needed), but SERFIQ use euclidean distance. If you normalize here, it is equivalent to cosine distance!
https://github.com/pterhoer/FaceImageQuality/blob/d9eff503098e16c622b0fb37c4d5859a6f6b49c4/face_image_quality.py#L262

> Since Gal et al. [12] proofed that applying dropout repetitively on a network approximates the uncertainty of a Gaussian process [33], the euclidean distance is a suitable choice for d(xi, xj ).
* Second, the batch normalization operation here is incomprehensible, Why?
https://github.com/pterhoer/FaceImageQuality/blob/d9eff503098e16c622b0fb37c4d5859a6f6b49c4/face_image_quality.py#L187-L188

**Comment by pterhoer** [comment]
Hi Walstruzz,

thank you for your interest in this work!

1) You are right, the euclidean distance of two unit-lenght vectors is equivalent to the cosine similarity of the unnormalized vectors. Therefore, the euclidean distance measure can be replaced with cosine-distance. This will shift the quality values, but the relative order of quality values will be preserved. Meaning, the face quality assessment performance will be the same.

2) Batch normalization is not necessary for SER-FIQ. I guesse this is still an artifact of previous research. It does not hurt, but it is not necessary either.

Best regards
Philipp
