### ISSUE TITLE
关于实际使用情况的一些反馈意见

### ISSUE THREAD

**Issue by XHQC** [pterhoer/FaceImageQuality#32]
@pterhoer 首先非常感谢作者的工作！
通过一些实际环境中使用数据测试的情况描述：
在完整的脸上可以预测正确结果
对于遮挡的人脸（自我遮挡、物体遮挡）和残缺的人脸这些也是评定为低质量的人脸，在这种情况下不能正确评定，这些情况是实际应用中关注的重点

在此，请教下是否有合适的处理方法

**Comment by jankolf** [comment]
Hi,
could you please be more specific with your question in English? [Here was linked how to approach the procedure for the scores and finding a threshold](https://github.com/pterhoer/FaceImageQuality/issues/29#issuecomment-741791568).

Best,
Jan
