### ISSUE TITLE
How to Make .npy File?

### ISSUE THREAD

**Issue by SYNota** [pterhoer/FaceImageQuality#36]
@pterhoer @jankolf 

Hi, smart guys !

I want to make own .npy files in data folder.
but i cant make this file.. 

plz help me 😥

**Comment by SYNota** [comment]
solved it !!!!

**Comment by jankolf** [comment]
Hi,
you can save numpy-arrays bei calling numpy.save(file-path, array). [You can have a look at the documentation of numpy](https://numpy.org/doc/stable/reference/generated/numpy.save.html).

A code snippet could look like this:
```
import numpy
data = numpy.array(...)
numpy.save("./data/my_data.npy", data)
```
If you have problems saving your data, make sure that you have read/write access to the location you are writing your data to.
Also, make sure that the path you are passing to save function is correct.

You can load data by calling the numpy.load function ([Documentation](https://numpy.org/doc/stable/reference/generated/numpy.load.html)):
```
data  = numpy.load("./data/my_data.npy")
```
