### ISSUE TITLE
About pre_fc1_weights.npy&pre_fc1_bias.npy

### ISSUE THREAD

**Issue by lxzatwowone1** [pterhoer/FaceImageQuality#37]
Hello, I dont know how to create them, and  can they use in every recongition-model？

**Comment by jankolf** [comment]
Hi,
the weights are extracted from the used Arcface/Insightface network's Dropout layers and are then loaded into Keras for predicting the dropout values. You can find a more detailed explanation [here](https://github.com/pterhoer/FaceImageQuality/issues/34#issuecomment-766141202).
Therefore you can not use these weights for every network, only for the specific Insightface one.
If you want to use your own network, you have to extract the Dropout/Fully-Connected weights.

Best,
Jan
