### ISSUE TITLE
模型车前向传播速度太慢了吧？

### ISSUE THREAD

**Issue by ZhengHui-Z** [pterhoer/FaceImageQuality#39]
100/100 [00:04<00:00, 23.29pass/s]

测试平台 RTX3090

**Comment by jankolf** [comment]
Hello,
we kindly ask you to use English as we cannot offer support for other languages.
The sample code is intended to illustrate the procedure. This methodology can also be modelled by own networks or forward passes, e.g. by not propagating an input 100 times through the network, but first multiplying/appending the input 100 times and then propagating the input (100, ...) through the network.
If there is interest, we can offer further information for a more performant Mxnet implementation.

With kind regards,
Jan
