### ISSUE TITLE
SERFIQ is not working correctly

### ISSUE THREAD

**Issue by kn-ru** [pterhoer/FaceImageQuality#41]
Greetings. Tried to reproduce the result of your solution. I decided to run the code as it is without changing anything.
Environment: AWS MX 1.8 (+Keras2) with Python3 (CUDA + and Intel MKL-DNN)

```
from face_image_quality import InsightFace, SERFIQ, get_embedding_quality
import cv2

insightface_model = InsightFace()
ser_fiq = SERFIQ()
test_img = cv2.imread("./data/test_img2.jpeg")
embedding, score = get_embedding_quality(test_img,
                                               insightface_model,
                                               ser_fiq
                                               )
print("SER-FIQ quality score of image 1 is", score)
SER-FIQ quality score of image 1 is 0.9999999850988388
```

At the same time, by sending almost any image, I get a score : 0.9999
Please tell me what could be wrong?

**Comment by pterhoer** [comment]
Hi kn-ru,

the quality values created by SER-FIQ are depending on the used face recognition model.
The same goes for the range of the quality values that are generated.
These often appear in a very narrow range. For instance, with the InsightFace model used in the paper it was around 0.87-0.89.
Depending on the used model, your result might actually be correct and just in a inconvenient range.
A simple MinMax or Z-score scaling might solve your "problem".

Best
Philipp

**Comment by jankolf** [comment]
Hi kn-ru,
we have updated the repository to make the installation easier, also we have added a normalization term to the score. The scores should more distinguishable.
Please have a look at the new setup instructions and apply your images on the model provided in this repository and please tell us if the score of the images provided are still near 1.0.

Best,
Jan
