### ISSUE TITLE
Which Mxnet version should we install?

### ISSUE THREAD

**Issue by HOMGH** [pterhoer/FaceImageQuality#54]
Hi,
Which Mxnet version should we install? I'm getting tones of error regarding mxnet. My Cuda version is 9.1. So I installed mxnet-cu91. Then I got "cannot import name 'ImageRecordInt8Iter' from 'mxnet.io.io' " error and I changed some depricated functions to fix it. Now I'm getting "cannot import name 'multi_sum_sq' from 'mxnet.ndarray' " error and have no idea how to fix it as I didn't find anything online about that error.
Please advise.
Thanks.

**Comment by rommeldias** [comment]
Hi,

Same problem here. What version of both CUDA and mxnet should we install?

Thanks.

**Comment by jankolf** [comment]
Hi @HOMGH and @rommeldias 
in case you are using pytorch, you can have a look at my [re-implementation](https://github.com/jankolf/ser-fiq-pytorch). It is easier to setup than mxnet.

Best,
Jan
