### ISSUE TITLE
There are some dependency missing.

### ISSUE THREAD

**Issue by haak0** [pterhoer/FaceImageQuality#6]
Dear authors, in this repo, there's some dependencies not specified, which prevents running the code straightly.
Such as
1. mtcnn_detector?
2. insightface model version?

btw, I'm not familiar with face toolkits.
thanks for ur time.

**Comment by hegc** [comment]
you can download code&model from [https://github.com/deepinsight/insightface)]

**Comment by jankolf** [comment]
Hi,
as hegc has already described, the Insightface repository must be downloaded and unpacked. The place is now called **_$Insightface_**. Also a pre-trained model must be downloaded and put into **_$Insightface/models_** folder. [We recommend "_LResNet100E-IR,ArcFace@ms1m-refine-v2_" model from the model zoo of Insightface](https://github.com/deepinsight/insightface/wiki/Model-Zoo#31-lresnet100e-irarcfacems1m-refine-v2).
The path **_$Insightface_** can be passed to the Insightface class with the parameter insightface_path.
The MTCNN detector is then imported from the Insightface codebase.

If you have further questions, please do not hesitate to ask them.

Best,
Jan
