### ISSUE TITLE
environment.yml file broken

### ISSUE THREAD

**Issue by kartik-nighania** [pterhoer/FaceImageQuality#7]
Collecting package metadata (repodata.json): done
Solving environment: failed

ResolvePackageNotFound: 
  - scikit-image==0.15.0=py36h6538335_0
  - numpy==1.14.2=py36h5c71026_0
  - protobuf==3.11.4=py36h33f27b4_0
  - tornado==6.0.4=py36hfa6e2cd_0
  - cffi==1.14.0=py36h7a1dbc1_0
  - requests==2.18.4=py36h4371aae_1
  - urllib3==1.22=py36h276f60a_0
  - cryptography==2.9.2=py36h7a1dbc1_0
  - py-mxnet==1.2.1=py36hcd68555_0
  - libpng==1.6.37=h2a8f88b_0
  - openssl==1.1.1g=he774522_0
  - grpcio==1.27.2=py36h351948d_0
  - win_inet_pton==1.1.0=py36_0
  - pyreadline==2.1=py36_1
  - scikit-learn==0.20.1=py36hb854c30_0
  - sqlite==3.31.1=h2a8f88b_1
  - pillow==7.1.2=py36hcc1f983_0
  - pywavelets==1.0.3=py36h452e1ab_1
  - python==3.6.9=h5500b2f_0
  - cudatoolkit==9.0=1
  - zstd==1.3.7=h508b16e_0
  - freetype==2.10.2=hd328e21_0
  - libtiff==4.1.0=h56a325e_0
  - icc_rt==2019.0.0=h0cc432a_1
  - wincertstore==0.2=py36h7fe50ca_0
  - wrapt==1.12.1=py36he774522_1
  - libprotobuf==3.11.4=h7bd577a_0
  - jpeg==9b=hb83a4c4_2
  - zlib==1.2.11=h62dcd97_4
  - vc==14.1=h0510ff6_4
  - kiwisolver==1.2.0=py36h246c5b5_0
  - libopencv==3.4.1=h875b8b8_3
  - cytoolz==0.10.1=py36hfa6e2cd_0
  - yaml==0.1.7=hc54c509_2
  - h5py==2.10.0=py36h5e291fa_0
  - opencv==3.3.1=py36h20b85fd_1
  - tensorflow==1.14.0=eigen_py36hf4fd08c_0
  - pyyaml==5.3.1=py36he774522_0
  - tensorflow-base==1.14.0=eigen_py36hdbc3f0e_0
  - libmxnet==1.2.1=gpu_mkl_hdf6cc24_1
  - vs2015_runtime==14.16.27012=hf0eaf9b_1
  - hdf5==1.10.4=h7ebc959_0
  - matplotlib-base==3.1.0=py36h3e3dc42_0
  - tensorboard==1.14.0=py36he3c9ec2_0
  - xz==5.2.5=h62dcd97_0
  - tk==8.6.10=hfa6e2cd_0
  - scipy==1.1.0=py36hc28095f_0

**Comment by jankolf** [comment]
Hi,
I tried the .yml file on two systems and could setup the anaconda environment without any problem.
Could you please specify
- which OS you are using (we tested everything on Windows 10)
- the anaconda version you are currently using (we used conda 4.8.2)
- any error message you received except the one you posted

Did you run the command "conda env create -f environment.yml"?
Maybe it helps if you delete the last row of the .yml file ("prefix: C:\Users\jkolf\.conda\envs\serfiq").
Best,
Jan
