### ISSUE TITLE
SER-FIQ eval

### ISSUE THREAD

**Issue by thibault20cent** [pterhoer/FaceImageQuality#9]
Hello,

I'm trying to reproduce the paper result (error vs reject curve for LFW - ArcFace). Are you computing FMR 0.001 for every genuine and impostor pairs combination of LFW or are you using the official pairs protocol ?

**Comment by pterhoer** [comment]
Hi thibault20cent,

thanks for your interest in our work.

We computed all imposter and genuine pair comparisons on the whole dataset. Then, we filtered out pairs of low quality dependet on the defined quality threshold (for the error-vs-reject curves we evalutated all possible thresholds based on the whole quality rankings). To compute the verification performance, for instance, we reported the FNMR at a decision threshold for a FMR of 0.0001.

Best
Philipp
